version: '3.8'
services:
  backend:
    build:
      context: ./../src/backend
      dockerfile: Dockerfile
    env_file:
      - ../../.env.development
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
